pipeline {
    agent any
    stages {
        stage('git checkout') {
            steps {
                
                git branch: 'main', url: 'https://github.com/bhanukumari/docker'
            }
        }
    
        stage('terraform init') {
             steps {
                
                    sh 'terraform init'
                
            }
            
        }
         stage('terraform validate') {
             steps {
                
                    sh 'terraform validate'
                
            }
            
        }
         stage('terraform plan') {
             steps {
                
                    sh 'terraform plan'
                
            }
            
        }
          stage('terraform apply') {
             steps {
               
                    sh 'terraform destroy -auto-approve'
                    
                
            }
            
        }
    }

}
